//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hastaSikayetleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hastaSikayetleri()
        {
            this.muayenelers = new HashSet<muayeneler>();
        }
    
        public int hastaSikayetID { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public string hastaSikayeti { get; set; }
        public Nullable<int> hastaID { get; set; }
    
        public virtual hastalar hastalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<muayeneler> muayenelers { get; set; }
    }
}
