//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hastalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hastalar()
        {
            this.hastaKabuls = new HashSet<hastaKabul>();
            this.hastaSikayetleris = new HashSet<hastaSikayetleri>();
            this.randevulars = new HashSet<randevular>();
            this.recetelers = new HashSet<receteler>();
            this.tahlillerSonucs = new HashSet<tahlillerSonuc>();
        }
    
        public int hastaID { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string ŞİFRE { get; set; }
        public string ADRES { get; set; }
        public string TELEFON { get; set; }
        public string TC { get; set; }
        public Nullable<System.DateTime> DOĞUM_TARİHİ { get; set; }
        public string CİNSİYET { get; set; }
        public string MEDENİ_HAL { get; set; }
        public Nullable<System.DateTime> kayıtTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hastaKabul> hastaKabuls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hastaSikayetleri> hastaSikayetleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<randevular> randevulars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<receteler> recetelers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tahlillerSonuc> tahlillerSonucs { get; set; }
    }
}
