//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hastaKabul
    {
        public int hastaKabulID { get; set; }
        public string sikayet { get; set; }
        public int doktorID { get; set; }
        public int poliklinikID { get; set; }
        public Nullable<int> randevuID { get; set; }
        public string RandevuDurumu { get; set; }
        public Nullable<int> hastaID { get; set; }
    
        public virtual personeller personeller { get; set; }
        public virtual poliklinikler poliklinikler { get; set; }
        public virtual randevular randevular { get; set; }
        public virtual hastalar hastalar { get; set; }
        public virtual personeller personeller1 { get; set; }
        public virtual poliklinikler poliklinikler1 { get; set; }
    }
}
