//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class muayeneler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public muayeneler()
        {
            this.teshislers = new HashSet<teshisler>();
        }
    
        public int muayeneID { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<int> doktorID { get; set; }
        public Nullable<int> hastaID { get; set; }
        public Nullable<int> randevuID { get; set; }
        public string Istenilen_Tahliller { get; set; }
        public string Istenilen_Testler { get; set; }
        public string Detay { get; set; }
    
        public virtual hastaSikayetleri hastaSikayetleri { get; set; }
        public virtual personeller personeller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<teshisler> teshislers { get; set; }
    }
}
