//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personeller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personeller()
        {
            this.hastaKabuls = new HashSet<hastaKabul>();
            this.hastaKabuls1 = new HashSet<hastaKabul>();
            this.muayenelers = new HashSet<muayeneler>();
            this.randevulars = new HashSet<randevular>();
            this.recetelers = new HashSet<receteler>();
            this.teshislers = new HashSet<teshisler>();
            this.tahlillerSonucs = new HashSet<tahlillerSonuc>();
            this.tahlillerSonucs1 = new HashSet<tahlillerSonuc>();
        }
    
        public int personelID { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string ŞİFRE { get; set; }
        public string ADRES { get; set; }
        public bool CİNSİYET { get; set; }
        public string E_POSTA { get; set; }
        public Nullable<System.DateTime> DOĞUM_TARİHİ { get; set; }
        public int unvanID { get; set; }
        public Nullable<int> klinikID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hastaKabul> hastaKabuls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hastaKabul> hastaKabuls1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<muayeneler> muayenelers { get; set; }
        public virtual poliklinikler poliklinikler { get; set; }
        public virtual unvanlar unvanlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<randevular> randevulars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<receteler> recetelers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<teshisler> teshislers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tahlillerSonuc> tahlillerSonucs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tahlillerSonuc> tahlillerSonucs1 { get; set; }
    }
}
