//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class randevular
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public randevular()
        {
            this.hastaKabuls = new HashSet<hastaKabul>();
        }
    
        public int randevuID { get; set; }
        public Nullable<System.DateTime> RandevuTarihi { get; set; }
        public string RansevuSaati { get; set; }
        public Nullable<int> hastaID { get; set; }
        public Nullable<int> personelID { get; set; }
        public Nullable<int> poliklinikID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hastaKabul> hastaKabuls { get; set; }
        public virtual hastalar hastalar { get; set; }
        public virtual personeller personeller { get; set; }
        public virtual poliklinikler poliklinikler { get; set; }
    }
}
