//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tahlillerSonuc
    {
        public int tahlilSonucID { get; set; }
        public string aciklama { get; set; }
        public string sonuc { get; set; }
        public int tahlilID { get; set; }
        public Nullable<int> hastaID { get; set; }
        public Nullable<int> doktorID { get; set; }
        public Nullable<int> hemşireID { get; set; }
    
        public virtual hastalar hastalar { get; set; }
        public virtual personeller personeller { get; set; }
        public virtual personeller personeller1 { get; set; }
        public virtual tahliller tahliller { get; set; }
    }
}
